/**:
    ros__parameters:
#General robot properties
        _wheel_radius: 0.0355
        _wheel_base: 0.225
        _ticks_per_wheel_rev: 360

#For odometry specifics
        _initial_x: 0.0
        _initial_y: 0.0
        _initial_theta: 0.0
        _alpha_R: 1.0
        _alpha_L: 1.0
        _k_R: 0.1
        _k_L: 0.1
        _E_D: 1.0
        _E_B: 1.0
        _update_odometry: false
#For IMU
        _orientation_covariance: [.0001, .0, .0, .0, .0001, .0,.0,.0,.0001]
        _angular_velocity_covariance: [.001, .0, .0, .0, .001, .0,.0,.0,.001]
        _linear_acceleration_covariance: [.01, .0, .0, .0, .01, .0,.0,.0,.01]