/**:
    ros__parameters:
#General robot properties
        _wheel_radius: 0.0355
        _wheel_base: 0.225
        _ticks_per_wheel_rev: 360

#For odometry specifics
        _initial_x: 0.0
        _initial_y: 0.0
        _initial_theta: 0.0
        _alpha_R: 1.0
        _alpha_L: 1.0
        _k_R: 0.0005
        _k_L: 0.0005
        _E_D: 1.0
        _E_B: 1.4
        _update_odometry: false
        _dynamic_covariance: false
#For IMU
        _orientation_covariance: "[[0.0, 0.0,  0.0], [0.0, 0.0,  0.0], [0.0, 0.0,  0.0001826]]"
        _angular_velocity_covariance: "[[2.439e-05, 5.169e-07,  -2.577e-07], [5.169e-07, 6.305e-06,  -2.786e-07], [-2.577e-07, -2.786e-07,  2.267e-05]]"
        _linear_acceleration_covariance: "[[0.0001661, -9.742e-06,  -2.256e-05], [-9.742e-06, 0.0001219,  2.224e-05], [-2.256e-05, 2.224e-05,  0.0004139]]"
#For Hokuyo LiDAR:
        ip_address: ""
        #ip_port: 10940
        serial_port: "/dev/ttyACM-HOKUYO"
        serial_baud: 115200
        laser_frame_id: hokuyo
        angle_max: 2.60
        angle_min: -2.60
        publish_intensity: false
        publish_multiecho: false
        calibrate_time: true
        default_user_latency: 0.0
        diagnostics_tolerance: 0.05
        diagnostics_window_time: 5.0
        error_limit: 4
        get_detailed_status: false
        cluster: 2
        skip: 0 

