/**:
    ros__parameters:
#General robot properties
        _wheel_radius: 0.0355
        _wheel_base: 0.225
        _ticks_per_wheel_rev: 360

#For odometry specifics
        _initial_x: 0.0
        _initial_y: 0.0
        _initial_theta: 0.0
        _alpha_R: 1.0
        _alpha_L: 1.0
        _k_R: 0.0005
        _k_L: 0.0005
        _E_D: 1.0
        _E_B: 1.4
        _update_odometry: false
        _dynamic_covariance: false
#For IMU
        _orientation_covariance: "[[0.0, 0.0,  0.0], [0.0, 0.0,  0.0], [0.0, 0.0,  0.0001826]]"
        _angular_velocity_covariance: "[[2.439e-05, 5.169e-07,  -2.577e-07], [5.169e-07, 6.305e-06,  -2.786e-07], [-2.577e-07, -2.786e-07,  2.267e-05]]"
        _linear_acceleration_covariance: "[[0.0001661, -9.742e-06,  -2.256e-05], [-9.742e-06, 0.0001219,  2.224e-05], [-2.256e-05, 2.224e-05,  0.0004139]]"