/**:
    ros__parameters:
#General robot properties
        _wheel_radius: 0.0355
        _wheel_base: 0.225
        _ticks_per_wheel_rev: 360

#For odometry specifics
        _initial_x: 0.0
        _initial_y: 0.0
        _initial_theta: 0.0
        _alpha_R: 1.0
        _alpha_L: 1.0
        _k_R: 0.0005
        _k_L: 0.0005
        _E_D: 1.003855713758940
        _E_B: 0.941756780812767 #1.45
        _update_odometry: false
        _dynamic_covariance: false
        _publish_odom_tf: false
        _experimental_odom: false
        _dist_ratio: 0.9
        _yaw_ratio: 0.6

        _limit_covariance: "[[0.04,0.0,0.0],[0.0,0.09,0.0],[0.0,0.0,0.007615]]"
#For IMU
        _orientation_covariance: "[[1.63e-08, 0.0,  0.0], [0.0, 3.435e-09,  0.0], [0.0, 0.0,  0.001507]]"
        _angular_velocity_covariance: "[[0.0001552, 0.0,  0.0], [0.0, 0.000146,  0.0], [0.0, 0.0,  7.454e-03]]"
        _linear_acceleration_covariance: "[[0.01916, 0.0,  0.0], [0.0, 0.01971,  0.0], [0.0, 0.0,  0.09099]]"
#For Hokuyo LiDAR:
        ip_address: ""
        #ip_port: 10940
        serial_port: "/dev/ttyACM-HOKUYO"
        serial_baud: 115200
        laser_frame_id: hokuyo
        angle_max: 2.60
        angle_min: -2.60
        publish_intensity: false
        publish_multiecho: false
        calibrate_time: false
        default_user_latency: 0.0
        diagnostics_tolerance: 0.05
        diagnostics_window_time: 5.0
        error_limit: 4
        get_detailed_status: false
        cluster: 1
        skip: 0 

