
joy_node:
    ros__parameters:
        device_name: "Sony PLAYSTATION(R)3 Controller"
        deadzone: 0.05
        autorepeat_rate: 15.0
        sticky_buttons: false
        coalesce_interval_ms: 1